### ISSUE TITLE
发送POST请求 中文乱码

### ISSUE THREAD

**Issue by chenjunjie45** [group-robot/java-feishu-robot#4]
发送POST请求 中文乱码，已经设置了lang("zh_CN")，有解决方法吗

**Comment by hb0730** [comment]
@chenjunjie45 不好意思现在才看到,请问是那种模式,能否发出json格式的内容

**Comment by hb0730** [comment]
开发者长时间未反馈

**Comment by felix9ia** [comment]
现在这个问题依然存在...
![image](https://github.com/user-attachments/assets/58713d54-5125-4dd2-8763-106ca9f4a7be)

```
  PostMessage message = PostMessage.build().lang(
                PostLang.builder()
                        .lang("zh_cn")
                        .unit(
                                PostUnit.build()
                                        .title(orderDO.getShopName() + " 订单支付成功：" + orderNo)
                                        .addTags(
                                                PostTags.build().addTags(
                                                        TextTag.builder().text("商品为: " + goodsNames).build(),
                                                        TextTag.builder().text("支付金额为: " + orderDO.getTotalFee()).build(),
                                                        TextTag.builder().text("取餐码为: " + orderDO.getVerificationCode()).build(),
                                                        ATag.builder().text("请查看").href("http://www.example.com/").build(),
                                                        AtTag.builder().atAll(true).build()
                                                )
                                        )
                        )
                        .build()
        );
        FeishuRobotClient send = new FeishuRobotClient();
        send.setSecret(feishuRobotToken);
        send.setWebhook(feishuRobotWebhookUrl);
        FeishuRobotResponse feiShuRobotResponse = send.sendMessage(message);
        log.info("发送飞书通知成功:" + feiShuRobotResponse.getMsg());
```

**Comment by hb0730** [comment]
> 现在这个问题依然存在... ![image](https://private-user-images.githubusercontent.com/23549191/351349360-58713d54-5125-4dd2-8763-106ca9f4a7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODA5MzksIm5iZiI6MTcyMTc4MDYzOSwicGF0aCI6Ii8yMzU0OTE5MS8zNTEzNDkzNjAtNTg3MTNkNTQtNTEyNS00ZGQyLTg3NjMtMTA2Y2E5ZjRhN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAwMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMGFlZjg5ZjEyMGYzNTJiMWE4YTc3NzgzNTZkMjEzNjRkZmQ4MWY1MTVmNTgyM2IzZmJjYWNhMmFjMjI1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GliS-YNDo1fBvwpwDu9yxHeFV66uotJHrl1dpFwSs3c)
> 
> ```
>   PostMessage message = PostMessage.build().lang(
>                 PostLang.builder()
>                         .lang("zh_cn")
>                         .unit(
>                                 PostUnit.build()
>                                         .title(orderDO.getShopName() + " 订单支付成功：" + orderNo)
>                                         .addTags(
>                                                 PostTags.build().addTags(
>                                                         TextTag.builder().text("商品为: " + goodsNames).build(),
>                                                         TextTag.builder().text("支付金额为: " + orderDO.getTotalFee()).build(),
>                                                         TextTag.builder().text("取餐码为: " + orderDO.getVerificationCode()).build(),
>                                                         ATag.builder().text("请查看").href("http://www.example.com/").build(),
>                                                         AtTag.builder().atAll(true).build()
>                                                 )
>                                         )
>                         )
>                         .build()
>         );
>         FeishuRobotClient send = new FeishuRobotClient();
>         send.setSecret(feishuRobotToken);
>         send.setWebhook(feishuRobotWebhookUrl);
>         FeishuRobotResponse feiShuRobotResponse = send.sendMessage(message);
>         log.info("发送飞书通知成功:" + feiShuRobotResponse.getMsg());
> ```

并未复现
```java
 PostMessage message = PostMessage.build().lang(
                PostLang.builder()
                        .lang("zh_cn")
                        .unit(
                                PostUnit.build()
                                        .title("订单支付成功")
                                        .addTags(
                                                PostTags.build().addTags(
                                                        TextTag.builder().text("商品为: ").build(),
                                                        TextTag.builder().text("支付金额为: ").build(),
                                                        TextTag.builder().text("取餐码为: ").build(),
                                                        ATag.builder().text("请查看").href("http://www.example.com/").build(),
                                                        AtTag.builder().atAll(true).build()
                                                )
                                        )
                        )
                        .build()
        );
        String webhok = System.getenv("webhook");
        String secret = System.getenv("secret");
        FeishuRobotClient send = new FeishuRobotClient();
        send.setSecret(secret);
        send.setWebhook(webhok);
        FeishuRobotResponse feiShuRobotResponse = send.sendMessage(message);
        System.out.println(feiShuRobotResponse.getMsg());
```
结果:
<img width="540" alt="image" src="https://github.com/user-attachments/assets/a3b2354f-c7ea-4369-bd34-ed600408d48d">

建议追踪调查发送请求头信息以及请求体信息是否有误

**Comment by felix9ia** [comment]
![image](https://github.com/user-attachments/assets/666c9be5-0c5f-4609-aa0e-7b34a1063841)

build（）之后 message 为 null 正常吗 @hb0730

**Comment by hb0730** [comment]
[contentJsonStr](https://github.com/group-robot/java-feishu-robot/blob/66b0cebce0bfc2a171c5367bb9f05579d1a797e9/src/main/java/io/github/group/robot/feishu/core/model/PostMessage.java#L53)只是`PostMessage`中的属性

```java
    /**
     * 富文本json字符串,优先级高于lang,格式:
     * <PRE>
     * "post": {
     * "zh_cn": {}
     * }
     * <PRE>
     */
    private String contentJsonStr;
```

核心在于 [#toMessage](https://github.com/group-robot/java-feishu-robot/blob/66b0cebce0bfc2a171c5367bb9f05579d1a797e9/src/main/java/io/github/group/robot/feishu/core/model/PostMessage.java#L94)

**Comment by felix9ia** [comment]
![image](https://github.com/user-attachments/assets/4400bbbb-3ea5-4bc5-b7a0-499bd699c8e7)

![image](https://github.com/user-attachments/assets/fe6313cd-8f44-43c2-aa85-719df7b5f606)



@hb0730 看着也没问题，咱还需要我手动依赖 hutool-core,告知一下
```
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
            <version>5.8.29</version>
        </dependency>
```

**Comment by hb0730** [comment]
json序列化支持`gson`,`jackson`,`jsonb` 由 [hb0730/jsons](https://github.com/hb0730/jsons.git) 提供整合支持
http请求支持: `httpclient`,`hutool`,`okhttp3` 由 [hb0730/jhttps](https://github.com/hb0730/jhttps.git) 提供整合支持

我测试环境为
```maven
 <dependency>
            <groupId>io.github.group-robot</groupId>
            <artifactId>feishu-robot-core</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
            <version>5.8.28</version>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-http</artifactId>
            <version>5.8.28</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.17.0</version>
        </dependency>

```

**Comment by felix9ia** [comment]
![image](https://github.com/user-attachments/assets/cf8637a4-ad9e-476e-a1f9-336218b9b09c)

通过手动多引入 hutool-http 解决了
```
   <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
            <version>5.8.29</version>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-http</artifactId>
            <version>5.8.28</version>
        </dependency>
```
我项目用的是 fastjson2，但是这个问题和 json 工具无关，主要和  hutool-http 有关。
```
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.49</version>
        </dependency>
```


@hb0730 这个依赖导致的问题太隐性了，感觉还有优化的空间，希望大佬抽空优化！感谢！
