### ISSUE TITLE
feat Request: TextTag 可否增加一个属性支持换行

### ISSUE THREAD

**Issue by felix9ia** [group-robot/java-feishu-robot#7]
首先，工具的设计非常优雅！点赞！但想更优雅的换行排版

例如：TextTag.builder().text("这是一行文字").ending().build()

ending() 作为换行属性，或者 enter()

**Comment by hb0730** [comment]
可以尝试
```java
TextTag.builder().text("这是一行文字 \n").build()
```

**Comment by felix9ia** [comment]
PR: https://github.com/group-robot/java-feishu-robot/pull/8
